# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box = 'olenik/archnas'

  config.vm.provider 'virtualbox' do |v|
    v.name = 'archnas_test'
    v.customize ['modifyvm', :id, '--firmware', 'efi']
  end

  config.vm.provision 'shell', inline: <<-SHELL
    set -euo pipefail
    # Run tests?
  SHELL
end
