#!/usr/bin/env bash
set -euo pipefail

RUNTIME="${RUNTIME:-/usr/bin/docker}"
FRIGATE_RTSP_PASSWORD="$(jq -r .frigate.rtsp_password /etc/secrets.json)"

"$RUNTIME" run -d \
  --name frigate-systemd \
  --restart=always \
  --mount type=tmpfs,target=/tmp/cache,tmpfs-size=1000000000 \
  --device /dev/bus/usb:/dev/bus/usb \
  --device /dev/dri/renderD128 \
  --shm-size=128mb \
  -v $FRIGATE_MEDIA:/media/frigate \
  -v $FRIGATE_CONFIG:/config/config.yml \
  -v /etc/localtime:/etc/localtime:ro \
  -e FRIGATE_RTSP_PASSWORD="$FRIGATE_RTSP_PASSWORD" \
  -p 5000:5000 \
  -p 8554:8554 \
  -p 8555:8555/tcp \
  -p 8555:8555/udp \
  ghcr.io/blakeblackshear/frigate:stable

